# -*- coding: utf-8 -*-
"""funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPFn8QbkjpN0-oTmd9qG-5_ubD0xyKFt
"""

def explorar_dataframe(df, nombre_df="DataFrame"):
    """
    Muestra información básica y estadísticas descriptivas de un DataFrame.

    Parámetros:
    - df: pd.DataFrame - El DataFrame a explorar.
    - nombre_df: str - Nombre opcional del DataFrame para mostrar en los títulos.
    """
    print(f"# Algunos datos a conocer de la tabla {nombre_df}")
    print(f"Dimensiones: {df.shape[0]} filas y {df.shape[1]} columnas")
    print("*" * 50)
    print("\nDescripción de los datos:")
    print(df.info())
    print("*" * 50)
    print("\nEstadísticas descriptivas:")
    print(df.describe(include='all'))